import Foundation

/**
 *  Defines the lexical token domain of keywords as specified in GUI-o-Matic's protocol.
 */
enum Keyword: String {
    case menu_items =       "menu_items"
    case app_name =         "app_name"
    case app_icon =         "app_icon"
    case require_gui =      "require_gui"
    case main_window =      "main_window"
    case indicator =        "indicator"
    case font_styles =      "font_styles"
    case images =           "images"
    case http_cookies =     "http_cookies"
    case initial_status =   "initial_status"
    case id =               "id"
    case label =            "label"
    case sensitive =        "sensitive"
    case separator =        "separator"
    case args =             "args"
    case type =             "type"
    case op =               "op"
    case position =         "position"
    case show =             "show"
    case message =          "message"
    case close_quits =      "close_quits"
    case width =            "width"
    case height =           "height"
    case background =       "background"
    case action_items =     "action_items"
    case icon =             "icon"
    case title =            "title"
    case details =          "details"
    case notification =     "notification"
    case splash =           "splash"
    case bold =             "bold"
    case italic =           "italic"
    case family =           "family"
    case points =           "points"
    case imagePrefix =      "image:"
    case badge =            "badge"
    case status_displays =  "status_displays"
    case command =          "command"
    case progress_bar =     "progress_bar"
    case progress =         "progress"
    case color =            "color"
    case popup =            "popup"
    case alert =            "alert"
    case domain =           "domain"
    case key =              "key"
    case value =            "value"
    case remove =           "remove"
    case never_run_from_dmg = "_never_run_from_dmg"
}
